"""Create User, Club, Swipe models

Revision ID: e10bee0ff7d1
Revises: 
Create Date: 2025-11-15 13:15:16.447434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e10bee0ff7d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('meeting_time', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('year', sa.String(length=50), nullable=True),
    sa.Column('major', sa.String(length=255), nullable=True),
    sa.Column('interests', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('swipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('liked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('swipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_swipes_club_id'), ['club_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_swipes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_swipes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_swipes_user_id'))
        batch_op.drop_index(batch_op.f('ix_swipes_created_at'))
        batch_op.drop_index(batch_op.f('ix_swipes_club_id'))

    op.drop_table('swipes')
    op.drop_table('users')
    op.drop_table('clubs')
    # ### end Alembic commands ###
